build: add granularity test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -16,28 +16,68 @@ jobs:
         with:
           repository: ${{ github.event.pull_request.head.repo.full_name }}
           ref: ${{ github.head_ref }}
+          fetch-depth: 0
+      - name: cache docker layers
+        uses: satackey/action-docker-layer-caching@v0.0.8
+        with:
+          key: docker-layers-${{ hashFiles('Dockerfile') }}-${{ hashFiles('entrypoint.sh') }}
       - name: update code owners
         uses: ./
         with:
           distribution: 50
           path: .github/CODEOWNERS.test
       - name: verify contents of generated file
-        id: verify1
         continue-on-error: true
         run: |
-          grep -q ".gitignore matthias.fax@gmail.com" .github/CODEOWNERS.test
+          grep -q ".gitignore[ \t]*matthias.fax@gmail.com" .github/CODEOWNERS.test
           echo "::set-env name=status::success"
       - name: verify contents of generated file (fallback)
-        id: verify2
         continue-on-error: true
         run: |
-          grep -q ".gitignore matfax@users.noreply.github.com" .github/CODEOWNERS.test
+          grep -q ".gitignore[ \t]*matfax@users.noreply.github.com" .github/CODEOWNERS.test
           echo "::set-env name=status::success"
+      - name: verify lack of granularity
+        continue-on-error: true
+        run: |
+          grep -q "build.yml" .github/CODEOWNERS.test
+          echo "::set-env name=granular::success"
       - name: fail if neither address is matched
         if: env.status != 'success'
         run: |
           echo "::error:: the expected owner could not be found in the test file"
           exit 1
+      - name: fail if granularity is detected
+        if: env.granular == 'success'
+        run: |
+          echo "::error:: the test file contained granular file references"
+          exit 1
+      - uses: actions/upload-artifact@v2.1.4
+        with:
+          name: ${{ github.job }}-owners
+          path: .github/CODEOWNERS.test
+  granular:
+    name: test with granular input
+    runs-on: ubuntu-latest
+    steps:
+      - name: checkout code
+        uses: actions/checkout@v2.3.2
+        with:
+          repository: ${{ github.event.pull_request.head.repo.full_name }}
+          ref: ${{ github.head_ref }}
+          fetch-depth: 0
+      - name: cache docker layers
+        uses: satackey/action-docker-layer-caching@v0.0.8
+        with:
+          key: docker-layers-${{ hashFiles('Dockerfile') }}-${{ hashFiles('entrypoint.sh') }}
+      - name: update code owners
+        uses: ./
+        with:
+          distribution: 25
+          granular: true
+          path: .github/CODEOWNERS.test
+      - name: verify contents of generated file
+        run: |
+          grep -q "build.yml" .github/CODEOWNERS.test
       - uses: actions/upload-artifact@v2.1.4
         with:
           name: ${{ github.job }}-owners
@@ -51,22 +91,25 @@ jobs:
         with:
           repository: ${{ github.event.pull_request.head.repo.full_name }}
           ref: ${{ github.head_ref }}
+          fetch-depth: 0
+      - name: cache docker layers
+        uses: satackey/action-docker-layer-caching@v0.0.8
+        with:
+          key: docker-layers-${{ hashFiles('Dockerfile') }}-${{ hashFiles('entrypoint.sh') }}
       - name: update code owners
         uses: ./
         with:
           distribution: 101
           path: .github/CODEOWNERS.test
       - name: verify contents of generated file
-        id: verify1
         continue-on-error: true
         run: |
-          grep -q ".gitignore matthias.fax@gmail.com" .github/CODEOWNERS.test
+          grep -q ".gitignore[ \t]*matthias.fax@gmail.com" .github/CODEOWNERS.test
           echo "::set-env name=status::success"
       - name: verify contents of generated file (fallback)
-        id: verify2
         continue-on-error: true
         run: |
-          grep -q ".gitignore matfax@users.noreply.github.com" .github/CODEOWNERS.test
+          grep -q ".gitignore[ \t]*matfax@users.noreply.github.com" .github/CODEOWNERS.test
           echo "::set-env name=status::success"
       - name: fail if either address is matched
         if: env.status == 'success'
